name: isomod-GUI auto Windows x86_64 builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        install: 
          mingw-w64-x86_64-toolchain
          cmake
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
        msystem: mingw64          
        release: false

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.11'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'
        dir: '${{github.workspace}}/qt/'
        install-deps: 'true'

    - name: Configure CMake
      run: cmake -G "CodeBlocks - MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{env.Qt5_Dir}}/lib/cmake/" -DQt5_DIR=${{env.Qt5_Dir}}/lib/cmake/Qt5/ -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload the finished product
      uses: actions/upload-artifact@master
      with:
        name: isomod-GUI-Windows
        path: out
